//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aMAZEing_Escape.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::Microsoft.Xna.Framework.Input.Keys avancer {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["avancer"]));
            }
            set {
                this["avancer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys reculer {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["reculer"]));
            }
            set {
                this["reculer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Microsoft.Xna.Framework.Input.Keys gauche {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["gauche"]));
            }
            set {
                this["gauche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::Microsoft.Xna.Framework.Input.Keys droite {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["droite"]));
            }
            set {
                this["droite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys sauter {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["sauter"]));
            }
            set {
                this["sauter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftControl")]
        public global::Microsoft.Xna.Framework.Input.Keys sebaisser {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["sebaisser"]));
            }
            set {
                this["sebaisser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plein_ecran {
            get {
                return ((bool)(this["plein_ecran"]));
            }
            set {
                this["plein_ecran"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int index_resolution {
            get {
                return ((int)(this["index_resolution"]));
            }
            set {
                this["index_resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int sensibilite_souris {
            get {
                return ((int)(this["sensibilite_souris"]));
            }
            set {
                this["sensibilite_souris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float volume_musiques {
            get {
                return ((float)(this["volume_musiques"]));
            }
            set {
                this["volume_musiques"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float volume_sons {
            get {
                return ((float)(this["volume_sons"]));
            }
            set {
                this["volume_sons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public float densite_brouillard {
            get {
                return ((float)(this["densite_brouillard"]));
            }
            set {
                this["densite_brouillard"] = value;
            }
        }
    }
}
